print("Hello,What's your name?")
n=str(input())
print("Where do you live?")
l=str(input())
print("What's your age?")
a=int(input())
print("Hello")
print("My name is",n)
print("I live in",l)
print("My age is",a)
