print('Hello','What is your name?')
name=str(input())
print('What is your age')
age=int(input())
print('Where do you live in?')
live=str(input())
print('Hello','My name is',name,'My age is',age,'I live in',live,'Happy to know!','Welc to India')
